# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # Runs everyday at 0:00 AM UTC
    - cron: "0 0 * * *"

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: "latest"
            extended: true

      - name: Build Web
        run: hugo --minify

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
            deploy_key: ${{ secrets.PAGE_DEPLOY_SSH_ED25519 }}
            external_repository: WongPuiYan/WongPuiYan.github.io
            publish_branch: main
            publish_dir: ./public
            commit_message: ${{ github.event.head_commit.message }}
